version: '2'
services:
  web:
    image: ${IMAGE_NAME}
    ports:
      - "3000"
    networks:
       - ci
    labels:
      - "traefik.backend=data-driven"
      - "traefik.frontend.rule=Host:data-driven.ci.ukpds.org"
    volumes:
      - /etc/localtime:/etc/localtime:ro
networks:
  ci:
    external: true